export const projects = [
  {
    clientFirstName: "John",
    companyName: "Skyline Builders",
    email: "john@skyline.com",
    phone: "+1 415 234 5678",
    country: "USA",
    serviceType: "NEW_CONSTRUCTION",
    projectCategory: "RESIDENTIAL",
    budgetRange: "$100k – $200k",
    status: "In Progress",
  },
  {
    clientFirstName: "Aisha",
    companyName: "Urban Arch Studio",
    email: "aisha@urbanarch.co",
    phone: "+44 7700 900123",
    country: "UK",
    serviceType: "INTERIOR_DESIGN",
    projectCategory: "COMMERCIAL",
    budgetRange: "$50k – $100k",
    status: "Completed",
  },
  {
    clientFirstName: "Mahmud",
    companyName: "GreenScape Ltd",
    email: "mahmud@greenscape.com",
    phone: "+880 1712 345678",
    country: "Bangladesh",
    serviceType: "LANDSCAPE_DESIGN",
    projectCategory: "OTHER",
    budgetRange: "$30k – $60k",
    status: "Pending",
  },
];
